highlighter: rouge
encoding: UTF-8
future: false
markdown: kramdown
permalink: /:title
url: https://the-ensemblist.uk
author: The Ensemblist
title: The Ensemblist
sass:
  style: compressed
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
include:
  - ".well-known"
exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - SECURITY.md
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 
